### ISSUE TITLE
More descriptive or detailed readme

### ISSUE THREAD

**Issue by Lelehel** [UV-Lab/LIO-SAM_MID360_ROS2#2]
Hi,

Could you give a more detailed summary on what this repo should do? I assume it's a ROS2 mid-360 lidar bundle but could help if you would describe how to install or use. 

Thx

**Comment by gspark87** [comment]
Hello, 
This repository is a ROS2-based LIO-SAM using Livox MID360.

**Dependency)**
1. [Livox SDK2](https://github.com/Livox-SDK/Livox-SDK2)
2. [livox_ros_driver2](https://github.com/Livox-SDK/livox_ros_driver2)
3. [autorccar_interfaces](https://github.com/UV-Lab/autoRCcar_indoor/tree/main/ros2/src/autorccar_interfaces)

**Build)**
Build "autorccar_interfaces" first and LIO-SAM_MID360_ROS2

**Run)**
While connected to Livox MID-360,
`$ ros2 launch livox_ros_driver2 msg_MID360_launch.py`
`$ ros2 launch lio_sam run.launch.py`
